# Unsupervised Learning

## 1. K-means Clustering
> In this this exercise, you will implement the K-means algorithm and use it
for image compression.

### 1.1 Implementing K-means

> The K-means algorithm is a method to automatically cluster similar data examples together. The intuition behind K-means is an iterative procedure that starts by guess- ing the initial centroids, and then refines this guess by repeatedly assigning examples to their closest centroids and then recomputing the centroids based on the assignments.

#### 1.1.1 Finding Closest Centroids

For every example $i$ we set $c_{(i)} := j$ that minimizes $||x^{(i)}-\mu_j||^2$ where $c_{(i)}$ is the index of the centroid that is closest to $x^{(i)}$, and $\mu_j$ is the position (value) of the j'th centroid.

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [42]:
def find_closest_centroid(X, centroids):
    idx = np.zeros((X.shape[0], 1))
    #print(idx)
    for i in range(X.shape[0]):
        idx[i] = np.argmin(np.sqrt(np.sum((X[i,:] - centroids) **2, axis = 1))) + 1
        #print(idx[i])
    return idx

In [52]:
print(K)
print(X.shape)
print(X.shape[1])
print(np.zeros((K, X.shape[1])))
print(X[1,:])

3
(8, 2)
2
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[2 5]


In [61]:
print(np.zeros((3, X.shape[1])))
print(X[(clusters == 0+1).T[0],:])
print(X[(clusters == 1+1).T[0],:])
print(X[(clusters == 2+1).T[0],:])

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[ 2 10]]
[[8 4]
 [5 8]
 [7 5]
 [6 4]
 [4 9]]
[[2 5]
 [1 2]]


In [63]:
def compute_centroids(X, idx, K):
    centroids = np.zeros((K, X.shape[1]))
    for i in range(K):
        centroids[i,:] = np.mean(X[(idx == i+1).T[0],:], axis = 0)
        #print(centroids[i,:])
        #print(X[(idx == -i+1), :])
        #print(X[(idx == -i+1).T[0],:])
    return centroids

In [64]:
K = 3 # clusters
X = np.array([[2,10], [2,5], [8,4], [5,8], [7, 5], [6, 4], [1, 2], [4,9]])
# from excel A1, B1, C1 are initial centroids
initial_centroids = np.array([[2,10], [5,8], [1,2]])

In [65]:
clusters = find_closest_centroid(X, initial_centroids)
print(initial_centroids)
for i in range(X.shape[0]):
    print('X {} cluster{}'.format(X[i], clusters[i]))

[[ 2 10]
 [ 5  8]
 [ 1  2]]
X [ 2 10] cluster[1.]
X [2 5] cluster[3.]
X [8 4] cluster[2.]
X [5 8] cluster[2.]
X [7 5] cluster[2.]
X [6 4] cluster[2.]
X [1 2] cluster[3.]
X [4 9] cluster[2.]


In [66]:
print(X)
print(clusters)
print(K)

[[ 2 10]
 [ 2  5]
 [ 8  4]
 [ 5  8]
 [ 7  5]
 [ 6  4]
 [ 1  2]
 [ 4  9]]
[[1.]
 [3.]
 [2.]
 [2.]
 [2.]
 [2.]
 [3.]
 [2.]]
3


In [67]:
range(3)

range(0, 3)

In [69]:
new_centroids = compute_centroids(X, clusters, K)
print(new_centroids)
clusters = find_closest_centroid(X, new_centroids)
for i in range(X.shape[0]):
    print('X {} cluster {}'.format(X[i], clusters))

[[ 2.  10. ]
 [ 6.   6. ]
 [ 1.5  3.5]]
X [ 2 10] cluster [[1.]
 [3.]
 [2.]
 [2.]
 [2.]
 [2.]
 [3.]
 [1.]]
X [2 5] cluster [[1.]
 [3.]
 [2.]
 [2.]
 [2.]
 [2.]
 [3.]
 [1.]]
X [8 4] cluster [[1.]
 [3.]
 [2.]
 [2.]
 [2.]
 [2.]
 [3.]
 [1.]]
X [5 8] cluster [[1.]
 [3.]
 [2.]
 [2.]
 [2.]
 [2.]
 [3.]
 [1.]]
X [7 5] cluster [[1.]
 [3.]
 [2.]
 [2.]
 [2.]
 [2.]
 [3.]
 [1.]]
X [6 4] cluster [[1.]
 [3.]
 [2.]
 [2.]
 [2.]
 [2.]
 [3.]
 [1.]]
X [1 2] cluster [[1.]
 [3.]
 [2.]
 [2.]
 [2.]
 [2.]
 [3.]
 [1.]]
X [4 9] cluster [[1.]
 [3.]
 [2.]
 [2.]
 [2.]
 [2.]
 [3.]
 [1.]]


In [70]:
new_centroids = compute_centroids(X, clusters, K)
print(new_centroids)
clusters = find_closest_centroid(X, new_centroids)
for i in range(X.shape[0]):
    print('X {} cluster {}'.format(X[i], clusters))

[[3.   9.5 ]
 [6.5  5.25]
 [1.5  3.5 ]]
X [ 2 10] cluster [[1.]
 [3.]
 [2.]
 [1.]
 [2.]
 [2.]
 [3.]
 [1.]]
X [2 5] cluster [[1.]
 [3.]
 [2.]
 [1.]
 [2.]
 [2.]
 [3.]
 [1.]]
X [8 4] cluster [[1.]
 [3.]
 [2.]
 [1.]
 [2.]
 [2.]
 [3.]
 [1.]]
X [5 8] cluster [[1.]
 [3.]
 [2.]
 [1.]
 [2.]
 [2.]
 [3.]
 [1.]]
X [7 5] cluster [[1.]
 [3.]
 [2.]
 [1.]
 [2.]
 [2.]
 [3.]
 [1.]]
X [6 4] cluster [[1.]
 [3.]
 [2.]
 [1.]
 [2.]
 [2.]
 [3.]
 [1.]]
X [1 2] cluster [[1.]
 [3.]
 [2.]
 [1.]
 [2.]
 [2.]
 [3.]
 [1.]]
X [4 9] cluster [[1.]
 [3.]
 [2.]
 [1.]
 [2.]
 [2.]
 [3.]
 [1.]]


In [71]:
new_centroids = compute_centroids(X, clusters, K)
print(new_centroids)
clusters = find_closest_centroid(X, new_centroids)
for i in range(X.shape[0]):
    print('X {} cluster {}'.format(X[i], clusters))

[[3.66666667 9.        ]
 [7.         4.33333333]
 [1.5        3.5       ]]
X [ 2 10] cluster [[1.]
 [3.]
 [2.]
 [1.]
 [2.]
 [2.]
 [3.]
 [1.]]
X [2 5] cluster [[1.]
 [3.]
 [2.]
 [1.]
 [2.]
 [2.]
 [3.]
 [1.]]
X [8 4] cluster [[1.]
 [3.]
 [2.]
 [1.]
 [2.]
 [2.]
 [3.]
 [1.]]
X [5 8] cluster [[1.]
 [3.]
 [2.]
 [1.]
 [2.]
 [2.]
 [3.]
 [1.]]
X [7 5] cluster [[1.]
 [3.]
 [2.]
 [1.]
 [2.]
 [2.]
 [3.]
 [1.]]
X [6 4] cluster [[1.]
 [3.]
 [2.]
 [1.]
 [2.]
 [2.]
 [3.]
 [1.]]
X [1 2] cluster [[1.]
 [3.]
 [2.]
 [1.]
 [2.]
 [2.]
 [3.]
 [1.]]
X [4 9] cluster [[1.]
 [3.]
 [2.]
 [1.]
 [2.]
 [2.]
 [3.]
 [1.]]


In [72]:
new_centroids = compute_centroids(X, clusters, K)
print(new_centroids)
clusters = find_closest_centroid(X, new_centroids)
for i in range(X.shape[0]):
    print('X {} cluster {}'.format(X[i], clusters))

[[3.66666667 9.        ]
 [7.         4.33333333]
 [1.5        3.5       ]]
X [ 2 10] cluster [[1.]
 [3.]
 [2.]
 [1.]
 [2.]
 [2.]
 [3.]
 [1.]]
X [2 5] cluster [[1.]
 [3.]
 [2.]
 [1.]
 [2.]
 [2.]
 [3.]
 [1.]]
X [8 4] cluster [[1.]
 [3.]
 [2.]
 [1.]
 [2.]
 [2.]
 [3.]
 [1.]]
X [5 8] cluster [[1.]
 [3.]
 [2.]
 [1.]
 [2.]
 [2.]
 [3.]
 [1.]]
X [7 5] cluster [[1.]
 [3.]
 [2.]
 [1.]
 [2.]
 [2.]
 [3.]
 [1.]]
X [6 4] cluster [[1.]
 [3.]
 [2.]
 [1.]
 [2.]
 [2.]
 [3.]
 [1.]]
X [1 2] cluster [[1.]
 [3.]
 [2.]
 [1.]
 [2.]
 [2.]
 [3.]
 [1.]]
X [4 9] cluster [[1.]
 [3.]
 [2.]
 [1.]
 [2.]
 [2.]
 [3.]
 [1.]]
